/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "DateTime.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

DateTime::DateTime()
{
    m_date = U("");
    
}

DateTime::~DateTime()
{
}

void DateTime::validate() 
{
    // TODO: implement validation
}

web::json::value DateTime::toJson() const
{
    web::json::value val = web::json::value::object();
     
	val[U("date")] = ModelBase::toJson(m_date);
    

    return val;
}

void DateTime::fromJson(web::json::value& val)
{
    setDate(ModelBase::stringFromJson(val[U("date")]));
    
}

void DateTime::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	multipart->add(ModelBase::toHttpContent(namePrefix + U("date"), m_date));
    
}

void DateTime::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    setDate(ModelBase::stringFromHttpContent(multipart->getContent(U("date"))));
    
}
    
   
utility::string_t DateTime::getDate() const
{
	return m_date;
}
void DateTime::setDate(utility::string_t value)
{
	m_date = value;
    
}

}
}
}
}

