/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "Error.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Error::Error()
{
    m_Code = U("");
    m_Title = U("");
    m_TitleIsSet = false;
    m_Detail = U("");
    m_DetailIsSet = false;
    m_Message = U("");
    m_MessageIsSet = false;
    
}

Error::~Error()
{
}

void Error::validate() 
{
    // TODO: implement validation
}

web::json::value Error::toJson() const
{
    web::json::value val = web::json::value::object();
     
	val[U("code")] = ModelBase::toJson(m_Code);
    if(m_TitleIsSet)
    {
        val[U("title")] = ModelBase::toJson(m_Title);
    }
    if(m_DetailIsSet)
    {
        val[U("detail")] = ModelBase::toJson(m_Detail);
    }
    if(m_MessageIsSet)
    {
        val[U("message")] = ModelBase::toJson(m_Message);
    }
    

    return val;
}

void Error::fromJson(web::json::value& val)
{
    setCode(ModelBase::stringFromJson(val[U("code")]));
    if(val.has_field(U("title")))
    {
        setTitle(ModelBase::stringFromJson(val[U("title")]));
                
    }
    if(val.has_field(U("detail")))
    {
        setDetail(ModelBase::stringFromJson(val[U("detail")]));
                
    }
    if(val.has_field(U("message")))
    {
        setMessage(ModelBase::stringFromJson(val[U("message")]));
                
    }
    
}

void Error::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	multipart->add(ModelBase::toHttpContent(namePrefix + U("code"), m_Code));
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("title"), m_Title));
                
    }
    if(m_DetailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("detail"), m_Detail));
                
    }
    if(m_MessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("message"), m_Message));
                
    }
    
}

void Error::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    setCode(ModelBase::stringFromHttpContent(multipart->getContent(U("code"))));
    if(multipart->hasContent(U("title")))
    {
        setTitle(ModelBase::stringFromHttpContent(multipart->getContent(U("title"))));
                
    }
    if(multipart->hasContent(U("detail")))
    {
        setDetail(ModelBase::stringFromHttpContent(multipart->getContent(U("detail"))));
                
    }
    if(multipart->hasContent(U("message")))
    {
        setMessage(ModelBase::stringFromHttpContent(multipart->getContent(U("message"))));
                
    }
    
}
    
   
utility::string_t Error::getCode() const
{
	return m_Code;
}
void Error::setCode(utility::string_t value)
{
	m_Code = value;
    
}
utility::string_t Error::getTitle() const
{
	return m_Title;
}
void Error::setTitle(utility::string_t value)
{
	m_Title = value;
    m_TitleIsSet = true;
}
bool Error::titleIsSet() const
{
    return m_TitleIsSet;
}
void Error::unsetTitle() 
{
    m_TitleIsSet = false;
}
utility::string_t Error::getDetail() const
{
	return m_Detail;
}
void Error::setDetail(utility::string_t value)
{
	m_Detail = value;
    m_DetailIsSet = true;
}
bool Error::detailIsSet() const
{
    return m_DetailIsSet;
}
void Error::unsetDetail() 
{
    m_DetailIsSet = false;
}
utility::string_t Error::getMessage() const
{
	return m_Message;
}
void Error::setMessage(utility::string_t value)
{
	m_Message = value;
    m_MessageIsSet = true;
}
bool Error::messageIsSet() const
{
    return m_MessageIsSet;
}
void Error::unsetMessage() 
{
    m_MessageIsSet = false;
}

}
}
}
}

