/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "InputOutput_attributes.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

InputOutput_attributes::InputOutput_attributes()
{
    m_Created_atIsSet = false;
    m_Updated_atIsSet = false;
    
}

InputOutput_attributes::~InputOutput_attributes()
{
}

void InputOutput_attributes::validate() 
{
    // TODO: implement validation
}

web::json::value InputOutput_attributes::toJson() const
{
    web::json::value val = web::json::value::object();
     
	val[U("input_parameters")] = ModelBase::toJson(m_Input_parameters);
    val[U("output_parameters")] = ModelBase::toJson(m_Output_parameters);
    if(m_Created_atIsSet)
    {
        val[U("created_at")] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        val[U("updated_at")] = ModelBase::toJson(m_Updated_at);
    }
    

    return val;
}

void InputOutput_attributes::fromJson(web::json::value& val)
{
    std::shared_ptr<Object> newInput_parameters(nullptr);
    newInput_parameters->fromJson(val[U("input_parameters")]);
    setInputParameters( newItem );
    std::shared_ptr<Object> newOutput_parameters(nullptr);
    newOutput_parameters->fromJson(val[U("output_parameters")]);
    setOutputParameters( newItem );
    if(val.has_field(U("created_at")))
    {
        if(!val[U("created_at")].is_null()) 
        {
            std::shared_ptr<DateTime> newItem(new DateTime());
            newItem->fromJson(val[U("created_at")]);
            setCreatedAt( newItem );
        }
                
    }
    if(val.has_field(U("updated_at")))
    {
        if(!val[U("updated_at")].is_null()) 
        {
            std::shared_ptr<DateTime> newItem(new DateTime());
            newItem->fromJson(val[U("updated_at")]);
            setUpdatedAt( newItem );
        }
                
    }
    
}

void InputOutput_attributes::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	m_Input_parameters->toMultipart(multipart, U("input_parameters."));
    m_Output_parameters->toMultipart(multipart, U("output_parameters."));
    if(m_Created_atIsSet)
    {
        if (m_Created_at.get())
        {
            m_Created_at->toMultipart(multipart, U("created_at."));
        }
                
    }
    if(m_Updated_atIsSet)
    {
        if (m_Updated_at.get())
        {
            m_Updated_at->toMultipart(multipart, U("updated_at."));
        }
                
    }
    
}

void InputOutput_attributes::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    std::shared_ptr<Object> newInput_parameters(nullptr);
    newInput_parameters->fromMultiPart(multipart, U("input_parameters."));
    setInputParameters( newInput_parameters );
    std::shared_ptr<Object> newOutput_parameters(nullptr);
    newOutput_parameters->fromMultiPart(multipart, U("output_parameters."));
    setOutputParameters( newOutput_parameters );
    if(multipart->hasContent(U("created_at")))
    {
        if(multipart->hasContent(U("created_at")))
        {
            std::shared_ptr<DateTime> newItem(new DateTime());
            newItem->fromMultiPart(multipart, U("created_at."));
            setCreatedAt( newItem );
        }
                
    }
    if(multipart->hasContent(U("updated_at")))
    {
        if(multipart->hasContent(U("updated_at")))
        {
            std::shared_ptr<DateTime> newItem(new DateTime());
            newItem->fromMultiPart(multipart, U("updated_at."));
            setUpdatedAt( newItem );
        }
                
    }
    
}
    
   
std::shared_ptr<Object> InputOutput_attributes::getInputParameters() const
{
	return m_Input_parameters;
}
void InputOutput_attributes::setInputParameters(std::shared_ptr<Object> value)
{
	m_Input_parameters = value;
    
}
std::shared_ptr<Object> InputOutput_attributes::getOutputParameters() const
{
	return m_Output_parameters;
}
void InputOutput_attributes::setOutputParameters(std::shared_ptr<Object> value)
{
	m_Output_parameters = value;
    
}
std::shared_ptr<DateTime> InputOutput_attributes::getCreatedAt() const
{
	return m_Created_at;
}
void InputOutput_attributes::setCreatedAt(std::shared_ptr<DateTime> value)
{
	m_Created_at = value;
    m_Created_atIsSet = true;
}
bool InputOutput_attributes::created_atIsSet() const
{
    return m_Created_atIsSet;
}
void InputOutput_attributes::unsetCreated_at() 
{
    m_Created_atIsSet = false;
}
std::shared_ptr<DateTime> InputOutput_attributes::getUpdatedAt() const
{
	return m_Updated_at;
}
void InputOutput_attributes::setUpdatedAt(std::shared_ptr<DateTime> value)
{
	m_Updated_at = value;
    m_Updated_atIsSet = true;
}
bool InputOutput_attributes::updated_atIsSet() const
{
    return m_Updated_atIsSet;
}
void InputOutput_attributes::unsetUpdated_at() 
{
    m_Updated_atIsSet = false;
}

}
}
}
}

