/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "Meta.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Meta::Meta()
{
    m_PaginationIsSet = false;
    
}

Meta::~Meta()
{
}

void Meta::validate() 
{
    // TODO: implement validation
}

web::json::value Meta::toJson() const
{
    web::json::value val = web::json::value::object();
     
	if(m_PaginationIsSet)
    {
        val[U("pagination")] = ModelBase::toJson(m_Pagination);
    }
    

    return val;
}

void Meta::fromJson(web::json::value& val)
{
    if(val.has_field(U("pagination")))
    {
        if(!val[U("pagination")].is_null()) 
        {
            std::shared_ptr<Pagination> newItem(new Pagination());
            newItem->fromJson(val[U("pagination")]);
            setPagination( newItem );
        }
                
    }
    
}

void Meta::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	if(m_PaginationIsSet)
    {
        if (m_Pagination.get())
        {
            m_Pagination->toMultipart(multipart, U("pagination."));
        }
                
    }
    
}

void Meta::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    if(multipart->hasContent(U("pagination")))
    {
        if(multipart->hasContent(U("pagination")))
        {
            std::shared_ptr<Pagination> newItem(new Pagination());
            newItem->fromMultiPart(multipart, U("pagination."));
            setPagination( newItem );
        }
                
    }
    
}
    
   
std::shared_ptr<Pagination> Meta::getPagination() const
{
	return m_Pagination;
}
void Meta::setPagination(std::shared_ptr<Pagination> value)
{
	m_Pagination = value;
    m_PaginationIsSet = true;
}
bool Meta::paginationIsSet() const
{
    return m_PaginationIsSet;
}
void Meta::unsetPagination() 
{
    m_PaginationIsSet = false;
}

}
}
}
}

