/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "Pagination.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Pagination::Pagination()
{
    m_Total = nullptr;
    m_Count = nullptr;
    m_Per_page = nullptr;
    m_Current_page = nullptr;
    m_Total_pages = nullptr;
    m_LinksIsSet = false;
    
}

Pagination::~Pagination()
{
}

void Pagination::validate() 
{
    // TODO: implement validation
}

web::json::value Pagination::toJson() const
{
    web::json::value val = web::json::value::object();
     
	val[U("total")] = ModelBase::toJson(m_Total);
    val[U("count")] = ModelBase::toJson(m_Count);
    val[U("per_page")] = ModelBase::toJson(m_Per_page);
    val[U("current_page")] = ModelBase::toJson(m_Current_page);
    val[U("total_pages")] = ModelBase::toJson(m_Total_pages);
    if(m_LinksIsSet)
    {
        val[U("links")] = ModelBase::toJson(m_Links);
    }
    

    return val;
}

void Pagination::fromJson(web::json::value& val)
{
    setTotal(ModelBase::int32_tFromJson(val[U("total")]));
    setCount(ModelBase::int32_tFromJson(val[U("count")]));
    setPerPage(ModelBase::int32_tFromJson(val[U("per_page")]));
    setCurrentPage(ModelBase::int32_tFromJson(val[U("current_page")]));
    setTotalPages(ModelBase::int32_tFromJson(val[U("total_pages")]));
    if(val.has_field(U("links")))
    {
        if(!val[U("links")].is_null()) 
        {
            std::shared_ptr<Pagination_links> newItem(new Pagination_links());
            newItem->fromJson(val[U("links")]);
            setLinks( newItem );
        }
                
    }
    
}

void Pagination::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	multipart->add(ModelBase::toHttpContent(namePrefix + U("total"), m_Total));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("count"), m_Count));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("per_page"), m_Per_page));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("current_page"), m_Current_page));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("total_pages"), m_Total_pages));
    if(m_LinksIsSet)
    {
        if (m_Links.get())
        {
            m_Links->toMultipart(multipart, U("links."));
        }
                
    }
    
}

void Pagination::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    setTotal(ModelBase::int32_tFromHttpContent(multipart->getContent(U("total"))));
    setCount(ModelBase::int32_tFromHttpContent(multipart->getContent(U("count"))));
    setPerPage(ModelBase::int32_tFromHttpContent(multipart->getContent(U("per_page"))));
    setCurrentPage(ModelBase::int32_tFromHttpContent(multipart->getContent(U("current_page"))));
    setTotalPages(ModelBase::int32_tFromHttpContent(multipart->getContent(U("total_pages"))));
    if(multipart->hasContent(U("links")))
    {
        if(multipart->hasContent(U("links")))
        {
            std::shared_ptr<Pagination_links> newItem(new Pagination_links());
            newItem->fromMultiPart(multipart, U("links."));
            setLinks( newItem );
        }
                
    }
    
}
    
   
int32_t Pagination::getTotal() const
{
	return m_Total;
}
void Pagination::setTotal(int32_t value)
{
	m_Total = value;
    
}
int32_t Pagination::getCount() const
{
	return m_Count;
}
void Pagination::setCount(int32_t value)
{
	m_Count = value;
    
}
int32_t Pagination::getPerPage() const
{
	return m_Per_page;
}
void Pagination::setPerPage(int32_t value)
{
	m_Per_page = value;
    
}
int32_t Pagination::getCurrentPage() const
{
	return m_Current_page;
}
void Pagination::setCurrentPage(int32_t value)
{
	m_Current_page = value;
    
}
int32_t Pagination::getTotalPages() const
{
	return m_Total_pages;
}
void Pagination::setTotalPages(int32_t value)
{
	m_Total_pages = value;
    
}
std::shared_ptr<Pagination_links> Pagination::getLinks() const
{
	return m_Links;
}
void Pagination::setLinks(std::shared_ptr<Pagination_links> value)
{
	m_Links = value;
    m_LinksIsSet = true;
}
bool Pagination::linksIsSet() const
{
    return m_LinksIsSet;
}
void Pagination::unsetLinks() 
{
    m_LinksIsSet = false;
}

}
}
}
}

