/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "Pagination_links.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Pagination_links::Pagination_links()
{
    m_Next = U("");
    m_NextIsSet = false;
    m_Previous = U("");
    m_PreviousIsSet = false;
    
}

Pagination_links::~Pagination_links()
{
}

void Pagination_links::validate() 
{
    // TODO: implement validation
}

web::json::value Pagination_links::toJson() const
{
    web::json::value val = web::json::value::object();
     
	if(m_NextIsSet)
    {
        val[U("next")] = ModelBase::toJson(m_Next);
    }
    if(m_PreviousIsSet)
    {
        val[U("previous")] = ModelBase::toJson(m_Previous);
    }
    

    return val;
}

void Pagination_links::fromJson(web::json::value& val)
{
    if(val.has_field(U("next")))
    {
        setNext(ModelBase::stringFromJson(val[U("next")]));
                
    }
    if(val.has_field(U("previous")))
    {
        setPrevious(ModelBase::stringFromJson(val[U("previous")]));
                
    }
    
}

void Pagination_links::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	if(m_NextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("next"), m_Next));
                
    }
    if(m_PreviousIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("previous"), m_Previous));
                
    }
    
}

void Pagination_links::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    if(multipart->hasContent(U("next")))
    {
        setNext(ModelBase::stringFromHttpContent(multipart->getContent(U("next"))));
                
    }
    if(multipart->hasContent(U("previous")))
    {
        setPrevious(ModelBase::stringFromHttpContent(multipart->getContent(U("previous"))));
                
    }
    
}
    
   
utility::string_t Pagination_links::getNext() const
{
	return m_Next;
}
void Pagination_links::setNext(utility::string_t value)
{
	m_Next = value;
    m_NextIsSet = true;
}
bool Pagination_links::nextIsSet() const
{
    return m_NextIsSet;
}
void Pagination_links::unsetNext() 
{
    m_NextIsSet = false;
}
utility::string_t Pagination_links::getPrevious() const
{
	return m_Previous;
}
void Pagination_links::setPrevious(utility::string_t value)
{
	m_Previous = value;
    m_PreviousIsSet = true;
}
bool Pagination_links::previousIsSet() const
{
    return m_PreviousIsSet;
}
void Pagination_links::unsetPrevious() 
{
    m_PreviousIsSet = false;
}

}
}
}
}

