/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "ProcessCollection_1.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ProcessCollection_1::ProcessCollection_1()
{
    m_MetaIsSet = false;
    
}

ProcessCollection_1::~ProcessCollection_1()
{
}

void ProcessCollection_1::validate() 
{
    // TODO: implement validation
}

web::json::value ProcessCollection_1::toJson() const
{
    web::json::value val = web::json::value::object();
     
	{
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Data )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val[U("data")] = web::json::value::array(jsonArray);
            }
    if(m_MetaIsSet)
    {
        val[U("meta")] = ModelBase::toJson(m_Meta);
    }
    

    return val;
}

void ProcessCollection_1::fromJson(web::json::value& val)
{
    {
        m_Data.clear();
        std::vector<web::json::value> jsonArray;
                for( auto& item : val[U("data")].as_array() )
        {
            
            if(item.is_null()) 
            {
                m_Data.push_back( std::shared_ptr<Process>(nullptr) );
            }
            else
            {
                std::shared_ptr<Process> newItem(new Process());
                newItem->fromJson(item);
                m_Data.push_back( newItem );
            }
            
        }
    }
    if(val.has_field(U("meta")))
    {
        if(!val[U("meta")].is_null()) 
        {
            std::shared_ptr<MetaLog> newItem(new MetaLog());
            newItem->fromJson(val[U("meta")]);
            setMeta( newItem );
        }
                
    }
    
}

void ProcessCollection_1::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	{
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Data )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        multipart->add(ModelBase::toHttpContent(namePrefix + U("data"), web::json::value::array(jsonArray), U("application/json")));
            }
    if(m_MetaIsSet)
    {
        if (m_Meta.get())
        {
            m_Meta->toMultipart(multipart, U("meta."));
        }
                
    }
    
}

void ProcessCollection_1::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    {
        m_Data.clear();
                
        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("data"))));
        for( auto& item : jsonArray.as_array() )
        {
            
            if(item.is_null()) 
            {
                m_Data.push_back( std::shared_ptr<Process>(nullptr) );
            }
            else
            {
                std::shared_ptr<Process> newItem(new Process());
                newItem->fromJson(item);
                m_Data.push_back( newItem );
            }
            
        }
    }
    if(multipart->hasContent(U("meta")))
    {
        if(multipart->hasContent(U("meta")))
        {
            std::shared_ptr<MetaLog> newItem(new MetaLog());
            newItem->fromMultiPart(multipart, U("meta."));
            setMeta( newItem );
        }
                
    }
    
}
    
   
std::vector<std::shared_ptr<Process>>& ProcessCollection_1::getData()
{
	return m_Data;
}
std::shared_ptr<MetaLog> ProcessCollection_1::getMeta() const
{
	return m_Meta;
}
void ProcessCollection_1::setMeta(std::shared_ptr<MetaLog> value)
{
	m_Meta = value;
    m_MetaIsSet = true;
}
bool ProcessCollection_1::metaIsSet() const
{
    return m_MetaIsSet;
}
void ProcessCollection_1::unsetMeta() 
{
    m_MetaIsSet = false;
}

}
}
}
}

