/**
 * ProcessMaker API
 * This ProcessMaker Core API provide access to the new generation engine with BPMN 2.0 support. The current Alpha 1.0 version supports  the part of BPM system functionality like process import, process execution, task assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: alpha-program@processmaker.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#include "ResultSuccess_meta.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ResultSuccess_meta::ResultSuccess_meta()
{
    m_Code = U("");
    m_Title = U("");
    m_TitleIsSet = false;
    
}

ResultSuccess_meta::~ResultSuccess_meta()
{
}

void ResultSuccess_meta::validate() 
{
    // TODO: implement validation
}

web::json::value ResultSuccess_meta::toJson() const
{
    web::json::value val = web::json::value::object();
     
	val[U("code")] = ModelBase::toJson(m_Code);
    if(m_TitleIsSet)
    {
        val[U("title")] = ModelBase::toJson(m_Title);
    }
    

    return val;
}

void ResultSuccess_meta::fromJson(web::json::value& val)
{
    setCode(ModelBase::stringFromJson(val[U("code")]));
    if(val.has_field(U("title")))
    {
        setTitle(ModelBase::stringFromJson(val[U("title")]));
                
    }
    
}

void ResultSuccess_meta::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

	multipart->add(ModelBase::toHttpContent(namePrefix + U("code"), m_Code));
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("title"), m_Title));
                
    }
    
}

void ResultSuccess_meta::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
	if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
	{
		namePrefix += U(".");
	}

    setCode(ModelBase::stringFromHttpContent(multipart->getContent(U("code"))));
    if(multipart->hasContent(U("title")))
    {
        setTitle(ModelBase::stringFromHttpContent(multipart->getContent(U("title"))));
                
    }
    
}
    
   
utility::string_t ResultSuccess_meta::getCode() const
{
	return m_Code;
}
void ResultSuccess_meta::setCode(utility::string_t value)
{
	m_Code = value;
    
}
utility::string_t ResultSuccess_meta::getTitle() const
{
	return m_Title;
}
void ResultSuccess_meta::setTitle(utility::string_t value)
{
	m_Title = value;
    m_TitleIsSet = true;
}
bool ResultSuccess_meta::titleIsSet() const
{
    return m_TitleIsSet;
}
void ResultSuccess_meta::unsetTitle() 
{
    m_TitleIsSet = false;
}

}
}
}
}

